---
title: "R Notebook"
output: html_notebook
---
```{r}
8+8
5+5
```

```{r}
age <- 17
age >= 18


vector <- c(100,200)
vector2 <- c(100,200)
names(vector) <- c("uno","dos")
vec <- vector+vector2
vec 
valor <- sum(vector)
valor
vector[1]
vector[c(1)]

vector5 <- c(a<-2,b<-3)
vector5
```

```{r}
matrix(1:9,byrow=TRUE,nrow=3)
```

```{r}
val_1 <- c(460.998,314.4)
empire_strike <- c(2980.475,247.9)
retun_jedi <- c(309.306,165.8)
box_office <- c(val_1,empire_strike,retun_jedi)

stars_wars_matrix <- matrix(box_office,byrow=TRUE,nrow=3)
stars_wars_matrix

region <- c("US","NON-US")
TITLES <- c("A NEW HOPE","THE EMPIRE STRIKES BACK","RETURN OF THE JEDI")
colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix)<-TITLES
stars_wars_matrix
```

```{r}
worldwide_vector <- rowSums(stars_wars_matrix)
worldwide_vector

all_wars_variable <-cbind(stars_wars_matrix,worldwide_vector)
all_wars_variable

worlwide_cols <- colSums(stars_wars_matrix)
worlwide_cols

all_wars_variable <- rbind(all_wars_variable,worlwide_cols)
all_wars_variable


no_us_all <- all_wars_variable[,2]
no_us_all

no_us_all <- all_wars_variable[1:3,2]
no_us_all

mean(no_us_all)

no_us_all <- all_wars_variable[1:3,2]
no_us_all <- no_us_all*.12
no_us_all 
```

factor
```{r}

sex_vector <- c("Male","Famale","Famale","Male","Male")
sex_vector <- factor(sex_vector)
sex_vector

temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperatur_vector <- factor(temperature_vector,order=TRUE,levels=c("Low","Medium","High"))
factor_temperatur_vector                
```

```{r}

surby_vector <- c("M","F","F","M","M")
factor_surby_vector <- factor(surby_vector)
factor_surby_vector
levels(factor_surby_vector) <- c("Male","Famale")
factor_surby_vector

summary(surby_vector)
summary(factor_surby_vector)

male <-factor_surby_vector[1]
famale<-factor_surby_vector[2]
```

```{r}

speed_vector <- c("mediun","slow","medium","fast")
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels=c("slow","medium","fast"))
factor_speed_vector
da2 <- factor_speed_vector[2]

da3 <- factor_speed_vector[1]

da2
da3

da2> da3

factor_speed_vector[1]




```

